apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfcdb-deployment
spec:
  selector:
    matchLabels:
      app: wfcdb
  replicas: 1
  template:
    metadata:
      labels:
        app: wfcdb
    spec:
      containers:
        - name: wfcdb-container
          image: pfropfen/imgdb
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_USER
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_USER
              value: "wfc"
            - name: MYSQL_PASSWORD
              value: "wfc"
            - name: MYSQL_DATABASE
              value: "maps"
          ports:
            - containerPort: 3306
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfcrabbit-deployment
spec:
  selector:
    matchLabels:
      app: wfcrabbit
  replicas: 1
  template:
    metadata:
      labels:
        app: wfcrabbit
    spec:
      containers:
        - name: wfcrabbit-container
          image: rabbitmq:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfcmanager-deployment
spec:
  selector:
    matchLabels:
      app: wfcmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: wfcmanager
    spec:
      containers:
        - name: wfcmanager-container
          image: pfropfen/imgmanager
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfcdistributor-deployment
spec:
  selector:
    matchLabels:
      app: wfcdistributor
  replicas: 1
  template:
    metadata:
      labels:
        app: wfcdistributor
    spec:
      containers:
        - name: wfcdistributor-container
          image: pfropfen/imgdistributor
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfchub-deployment
spec:
  selector:
    matchLabels:
      app: wfchub
  replicas: 1
  template:
    metadata:
      labels:
        app: wfchub
    spec:
      containers:
        - name: wfchub-container
          image: pfropfen/imghub
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfcworker-deployment
spec:
  selector:
    matchLabels:
      app: wfcworker
  replicas: 2
  template:
    metadata:
      labels:
        app: wfcworker
    spec:
      containers:
        - name: wfcworker-container
          image: pfropfen/imgworker
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
              protocol: TCP
